/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface RepoListItem {
        "name": string;
        "stargazersCount": number;
        "url": string;
    }
    interface ReposProfile {
        "match": MatchResults;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRepoListItemElement extends Components.RepoListItem, HTMLStencilElement {
    }
    var HTMLRepoListItemElement: {
        prototype: HTMLRepoListItemElement;
        new (): HTMLRepoListItemElement;
    };
    interface HTMLReposProfileElement extends Components.ReposProfile, HTMLStencilElement {
    }
    var HTMLReposProfileElement: {
        prototype: HTMLReposProfileElement;
        new (): HTMLReposProfileElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "repo-list-item": HTMLRepoListItemElement;
        "repos-profile": HTMLReposProfileElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface RepoListItem {
        "name"?: string;
        "stargazersCount"?: number;
        "url"?: string;
    }
    interface ReposProfile {
        "match"?: MatchResults;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "repo-list-item": RepoListItem;
        "repos-profile": ReposProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "repo-list-item": LocalJSX.RepoListItem & JSXBase.HTMLAttributes<HTMLRepoListItemElement>;
            "repos-profile": LocalJSX.ReposProfile & JSXBase.HTMLAttributes<HTMLReposProfileElement>;
        }
    }
}
